### ISSUE TITLE
certifi in requirements throws a security advisory

### ISSUE THREAD

**Issue by andrea-bistacchi** [gecos-lab/Py21#8]
Including `certifi` in requirements throws a security advisory.

![image](https://github.com/gecos-lab/Py21/assets/12087912/c2a98991-7e35-4ee4-afc2-c68b09f1a9a5)

It looks like it is used by Mozilla to manage certificates.

https://pypi.org/project/certifi/

Is this necessary?

**Comment by gbene** [comment]
I updated the requirements files to include only the main libraries. Certify is installed when installing one of these. I hope that now the dependabot is happy
